/****************************************************************************
* (C) 1999-2005 by BECK IPC GmbH
*
*  BECK IPC GmbH
*  Germany
*  
*  http://www.beck-ipc.com
*
* ---------------------------------------------------------------------------
*  Module        : CLIB.H
*  Function      : RTOS C library include file
* ---------------------------------------------------------------------------

   $Header: c:\prjPib\IPC@CHIP\CLib\CLIB.H, 10, 15.09.2006 11:39:53, Jack Gatrost$

*****************************************************************************/


#ifndef _CLIB_H_
  #define _CLIB_H_

  #include <BIOS_API.H>
  #include <CAN_API.H>
  #include <CGIAPI.H>
  #include <DNSAPI.H>
  #include <EXTDISK.H>
  #include <FOSSIL.H>
  #include <HELPER.H>
  #include <HWAPI.H>
  #include <I2C_API.H>
  #include <IPSEC.H>
  #include <SPIAPI.H>
  #include <PKTDRV.H>
  #include <RTOS.H>
  #include <RTXERR.H>
  #include <TCPIP.H>
  #include <usb_api.h>
  #include <usb_spec.h>

#endif // _CLIB_H_
